const actionTypes = {
    SET_LIST_VIEW: 'SET_LIST_VIEW',
    SET_DARK_THEME: 'SET_DARK_THEME',
    SET_FOOD_IMAGE: 'SET_FOOD_IMAGE',
    SET_BREWERIES: 'SET_BREWERIES',
    SET_RANDOM_BREWERY: 'SET_RANDOM_BREWERY',
    SET_BREWERIES_PER_PAGE: 'SET_BREWERIES_PER_PAGE',
    SET_SELECTED_TYPE: 'SET_SELECTED_TYPE',
    SET_BREWERY_NAME: 'SET_BREWERY_NAME',
    SET_BREWERY_CITY: 'SET_BREWERY_CITY',
    SET_BREWERY_STATE: 'SET_BREWERY_STATE',
    SET_RANDOM_PAGE: 'SET_RANDOM_PAGE',
}

export default actionTypes;